name: pytorch_cyclegan
channels:
- pytorch
- conda-forge
- defaults
dependencies:
- conda-forge::python=3.6
- conda-forge::torchvision
- conda-forge::seaborn=0.8.1
- conda-forge::numpy
- conda-forge::scipy=1.1.0
- conda-forge::urllib3
- conda-forge::pandas=0.20.3
- conda-forge::scikit-image
- conda-forge::umap-learn
- conda-forge::ggplot=0.11.5
- conda-forge::graphviz=2.38.0
- conda-forge::python-graphviz=0.8.4
- conda-forge::ipykernel=4.8.1
- conda-forge::ipywidgets=6.0.0
- conda-forge::widgetsnbextension=2.0.0
- conda-forge::nb_conda_kernels=2.1.0
- conda-forge::r-irdisplay=0.6.2
- conda-forge::r-irkernel=0.8.11
- conda-forge::r-ggplot2=2.2.1
- conda-forge::r-dplyr=0.7.6
- conda-forge::r-tidyr=0.8.0
- conda-forge::r-readr=1.1.1
- conda-forge::r-readxl=1.1.0
- conda-forge::r-cowplot=0.9.3
- conda-forge::r-heatmap3=1.1.1
- conda-forge::r-ggrepel=0.8.0
- conda-forge::r-optparse=1.6.0
- pip:
  - torch>=0.4.0
  - matplotlib==3.0.0
  - pillow
